### ISSUE TITLE
 Missing key in safetensors checkpoint: generator.weight

### ISSUE THREAD

**Issue by HURIMOZ** [eole-nlp/eole#117]
Hi, Iʻm using recipe wmt17 to build a bilingual translation model.
Iʻm now able to train the models but on inference I get this error:
```Missing key in safetensors checkpoint: generator.weight
``` 
The rest of the inference seems to run fine:
```[2024-09-25 06:08:22,476 INFO] Transforms applied: []
[2024-09-25 06:08:27,620 INFO] PRED SCORE: -0.1463, PRED PPL: 1.16 NB SENTENCES: 256
[2024-09-25 06:08:27,620 INFO] ESTIM SCORE: 1.0000, ESTIM PPL: 0.37 NB SENTENCES: 256
Time w/o python interpreter load/terminate:  5.920188903808594
``` 
In my models repository, three files are generated for every step saved:
- optimizer.pt
- model.00.safetensors
- vocab.json
- config.json

This is my bash command for inference:
```eole predict --src processed_data/test.src.bpe --model_path models/step_7000 --beam_size 5 --batch_size 2048 --batch_type tokens --output translations/test.trg.bpe --gpu 0```
What am I doing wrong to get error "Missing key in safetensors checkpoint: generator.weight"?

**Comment by vince62s** [comment]
This is not an error. The yaml config you are using is `share_decoder_embeddings: true` hence the model does not store twice the weights. We'll make this clearer and avoid the message in the log when this flag is ON.

**Comment by HURIMOZ** [comment]
Oh I see. Yes, makes sense now. Switched to false.
Thanks Vince!

**Comment by vince62s** [comment]
don't switch to false it's very fine to share embeddings between 1) src and tgt and 2) decoder and generator.
not sharing does not bring improvement
