### ISSUE TITLE
eole model average broken?

### ISSUE THREAD

**Issue by isanvicente** [eole-nlp/eole#136]
Hi!

I can successfully train bilingual MT models using the wmt17 recipe. I'm trying to average my best checkpoints (best - previous 4), but I'm getting the following error (command `$eole model average -models ckpt1 ckpt2 -output model_avg`):

```
Traceback (most recent call last):
  File "/mnt/nfs/NMT/venv_eole_gpu4/bin/eole", line 33, in <module>
    sys.exit(load_entry_point('eole', 'console_scripts', 'eole')())
  File "/mnt/nfs/NMT/eole/eole/bin/main.py", line 39, in main
    bin_cls.run(args)
  File "/mnt/nfs/NMT/eole/eole/bin/model/average_models.py", line 62, in run
    final = average_models(args.models, args.fp32)
  File "/mnt/nfs/NMT/eole/eole/bin/model/average_models.py", line 14, in average_models
    m = torch.load(model_file, map_location="cpu")
  File "/mnt/nfs/NMT/venv_eole_gpu4/lib/python3.10/site-packages/torch/serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/mnt/nfs/NMT/venv_eole_gpu4/lib/python3.10/site-packages/torch/serialization.py", line 1262, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: the STRING opcode argument must be quoted
```

My guess is [average_models](https://github.com/eole-nlp/eole/blob/5bf241b260e4fe8f97a29ac3a9455e8822a7a034/eole/bin/model/average_models.py#L6) function is trying to load a '.pt' formatted model (opennmt-py), but eole now uses safetensor format.

I've read #76 , but I'm not completely sure how to adapt the code to work with the new model checkpoint format. 

Thanks!

**Comment by vince62s** [comment]
Usually we don't use this but instead dynamic averaging. Check the setting average_decay if I recall properly

**Comment by francoishernandez** [comment]
Good catch. This tool was indeed not updated to fit the new checkpoint paradigm.
It's probably not that complicated to make it work with safetensors (just safe_load the weights from the .safetensors file, loop and build a new state_dict following the current logic, and save it back).
PR welcome if you're willing to contribute.

**Comment by isanvicente** [comment]
Hi! 

I can try and update the tool (not before next week).

@vince62s:  `-average_decay` defaults to 0 which means dynamic averaging it's not activated if I understand correctly (from open-nmt docs). If that's the way to go I'll give a try (I'll check Marian-nmt paper and implementation as well). 

Cheers.

**Comment by vince62s** [comment]
you can safely use: average_decay: 0.0005 if you train about 100-200K steps or more
