### ISSUE TITLE
The official docker image is not accessible

### ISSUE THREAD

**Issue by l-k-11235** [eole-nlp/eole#2]
I could not access it with `docker pull ghcr.io/eole-nlp/eole:0.0.1-ubuntu22.04-cuda12.1`.

**Comment by francoishernandez** [comment]
Thanks for reporting! Should be accessible now.
For reference, these image can always be rebuilt locally via the provided scripts and Dockerfiles in the [docker](https://github.com/eole-nlp/eole/tree/main/docker) directory.

**Comment by l-k-11235** [comment]
Thanks you ! I had managed to build it locally indeed.
