### ISSUE TITLE
Are spaces really needed in the dataset?

### ISSUE THREAD

**Issue by HURIMOZ** [eole-nlp/eole#61]
Looking at your recipe for WMT17, I notice that the dataset contains spaces between on either sides of the punctuation.
Is that required before training? If so, do you use a particular method?
Consider this example:
**I see that a space is needed, indeed, but only before the comma?!**
**I see that a space is needed , indeed , but only before the comma ? Cool ! ?**
Is this how we should prepare our corpus?

**Comment by vince62s** [comment]
The wmt17 recipe is very simplistic.
It uses an already tokenized dataset this is the reason why you will see those spaces.
In real life use cases you will need to use transforms and a tokenizer (look at wiki_103) otherwise I will try to add another recipe later on.
