### ISSUE TITLE
Error in multi-gpu training 

### ISSUE THREAD

**Issue by pdakwal** [eole-nlp/eole#79]
Hi,

I am trying to run a multi-gpu training for the wmt17 recipe configuration provided in the repo. I am using a single node with 4 GPUs. As instructed in FAQ, I set `CUDA_VISIBLE_DEVICES=0,1,2,3`. In the configuration file, I set `world_size: 4` and `gpu_ranks: [0,1,2,3]`. The training starts fine using all 4 GPUs but while saving the checkpoint, I get following error and training stops:

`[rank3]:[E ProcessGroupNCCL.cpp:563] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=45051, OpType=ALLGATHER, NumelIn=1, NumelOut=4, Timeout(ms)=60000) ran for 60044 milliseconds before timing out.
[rank3]:[E ProcessGroupNCCL.cpp:1537] [PG 0 Rank 3] Timeout at NCCL work: 45051, last enqueued NCCL work: 45051, last completed NCCL work: 45050.
[rank3]:[E ProcessGroupNCCL.cpp:577] [Rank 3] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank3]:[E ProcessGroupNCCL.cpp:583] [Rank 3] To avoid data inconsistency, we are taking the entire process down.
[rank3]:[E ProcessGroupNCCL.cpp:1414] [PG 0 Rank 3] Process group watchdog thread terminated with exception: [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=45051, OpType=ALLGATHER, NumelIn=1, NumelOut=4, Timeout(m
s)=60000) ran for 60044 milliseconds before timing out.
Exception raised from checkTimeout at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:565 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f07b7a7d897 in /home/ubuntu/venv-eole/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x1d2 (0x7f07b8d56c62 in /home/ubuntu/venv-eole/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::watchdogHandler() + 0x1a0 (0x7f07b8d5ba80 in /home/ubuntu/venv-eole/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x10c (0x7f07b8d5cdcc in /home/ubuntu/venv-eole/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xd3e95 (0x7f08047e3e95 in /opt/conda/bin/../lib/libstdc++.so.6)
frame #5: <unknown function> + 0x7ea7 (0x7f0805caeea7 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #6: clone + 0x3f (0x7f0805a7fa6f in /lib/x86_64-linux-gnu/libc.so.6)`

It works all good for single GPU training when setting `world_size: 1` and `gpu_ranks: [0]` with other parameters exactly the same.

On the same machine, OpenNMT-py training works all fine with 4 GPUs.

What I might be doing wrong? Or is it a possible bug? Please help.

Thanks

**Comment by vince62s** [comment]
in order to find out what is going on, did you try with 2 gpus ? 3 gpus ?
maybe increase this https://github.com/eole-nlp/eole/blob/main/eole/config/common.py#L34
to 120 sec
this the timeout for all processes to sync so if the process 0 (saving the model) takes too long maybe others time out.
I can't guarantee it comes from this but let's dig.

**Comment by vince62s** [comment]
@pdakwal were you able to track your issue ?
