### ISSUE TITLE
Pre-trained embeddings

### ISSUE THREAD

**Issue by HURIMOZ** [eole-nlp/eole#84]
Hi guys, Iʻve gotten my hands on Eole lately.
Iʻve been able to launch a couple of experiments based on your wmt17 recipe. Thanks for the recipe BTW.
Iʻm however wondering whether you are planning on integrating pre-trained embeddings functionality with Eole.
It would be great to have that work. We used GloVe and Fasttext pre-trained embeddings with OpenNMT back then and for low-resource languages they are of great help.
I see in your documentation that you have an FAQ about GloVe embeddings but it looks like the page is from an OpenNMT template as the "train eole" command will throw a Pydantic error when trying to use  pre-trained embeddings.

**Comment by vince62s** [comment]
don't expect improvement from this.
FYI I imported embeddings from llama 3 and trained and encoder decoder while freezing those embeddings, results were worse.

**Comment by francoishernandez** [comment]
Yes, this doc might not be fully up to date.
The feature is supposed to be working though. We retained it for the sake of facilitating potential experiments on the topic, but it's not really recommended for standard setups.

**Comment by HURIMOZ** [comment]
Please update your [page](https://eole-nlp.github.io/eole/docs/FAQ/pretrained_embeddings) on pre-trained embeddings as it still mentions onmt_train command.
Weʻve used pre-trained embeddings for our bilingual models with OpenNMT (both GloVe and fasttext) and they worked like a charm, they greatly enhanced our models. I donʻt know about Llama but weʻve used OpenNMT for bilingual NMT models and LLMs have not proved better at translation for low-resource languages. Iʻm not sure what is your plan with Eole but please tell us whether you will keep developing for bilingual NMT too or not.
