### ISSUE TITLE
eole_tokenize vs onmt_tokenize - Extra inputs are not permitted. Pydantic error

### ISSUE THREAD

**Issue by HURIMOZ** [eole-nlp/eole#89]
Iʻm trying to use **eole_tokenize** as mentioned [here](https://eole-nlp.github.io/eole/docs/concepts/transforms#opennmt-tokenizer).
Hereʻs the relevant part of my config file:
`data:
    corpus_1:
        path_src: processed_data/train.src.bpe.shuf
        path_tgt: processed_data/train.trg.bpe.shuf
    valid:
        path_src: processed_data/dev.src.bpe
        path_tgt: processed_data/dev.trg.bpe
transforms: [normalize, eole_tokenize, filtertoolong]
transforms_configs:
  normalize:
    norm_quote_commas: True
    norm_numbers: True
  eole_tokenize:
    src_subword_type: bpe
    tgt_subword_type: bpe
  filtertoolong:
    src_seq_length: 512
    tgt_seq_length: 512`

Using **eole-tokenize** I get this error:
`(TY-EN) ubuntu@ip-172-31-2-199:~/TY-EN/eole/recipes/wmt17$ eole build_vocab --config wmt17_enty.yaml --n_sample -1 # --num_threads 4
Traceback (most recent call last):
  File "/home/ubuntu/TY-EN/TY-EN/bin/eole", line 33, in <module>
    sys.exit(load_entry_point('eole', 'console_scripts', 'eole')())
  File "/home/ubuntu/TY-EN/eole/eole/bin/main.py", line 39, in main
    bin_cls.run(args)
  File "/home/ubuntu/TY-EN/eole/eole/bin/run/build_vocab.py", line 272, in run
    config = cls.build_config(args)
  File "/home/ubuntu/TY-EN/eole/eole/bin/run/__init__.py", line 42, in build_config
    config = cls.config_class(**config_dict)
  File "/home/ubuntu/TY-EN/TY-EN/lib/python3.10/site-packages/pydantic/main.py", line 193, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for BuildVocabConfig
transforms_configs.eole_tokenize
  Extra inputs are not permitted [type=extra_forbidden, input_value={'src_subword_type': 'bpe...gt_subword_type': 'bpe'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/extra_forbidden
`

Shall we stick to **onmt_tokenize** or is **eole-tokenize** usable at this time? If so, what is wrong in my config file?

**Comment by francoishernandez** [comment]
This is a doc renaming mishap. eole_tokenize does not exist. For now this shall remain onmt_tokenize.
For such documentation related mishap that you stumble upon, do not hesitate to open a PR.
