### ISSUE TITLE
Vocab format to use Sentencepiece

### ISSUE THREAD

**Issue by HURIMOZ** [eole-nlp/eole#93]
Hi, with OpenNMT-py weʻd run a script to convert the .vocab files generated by Sentencepiece into .onmt_vocab files so that openNMT-py could read them.
What vocab format does Eole accept?
How is the syntax for each vocab line exactly?

**Comment by francoishernandez** [comment]
I gather you are talking about this tool:
https://github.com/OpenNMT/OpenNMT-py/blob/master/tools/spm_to_vocab.py

It was ported to eole as [`eole tools spm_to_vocab`](https://github.com/eole-nlp/eole/blob/main/eole/bin/tools/spm_to_vocab.py)

I did not test this recently but there is no reason it should not work, as the vocab format has not changed.
It's a text file, with one token per line, and optionally the frequency (count) of each token appended to the line.
```
token1
token2
token3
...
```

```
token1 100
token2 80
token3 30
...
```

You can check the function that reads the vocab file for reference:
https://github.com/eole-nlp/eole/blob/b81cce1212c2951ad0ded344b338810cb7618ef6/eole/inputters/inputter.py#L87-L95
