### ISSUE TITLE
Sentencepiece

### ISSUE THREAD

**Issue by VolodymyrB** [eole-nlp/eole#97]
I had an issue with installing eole, setup.py could have double sentencepiece requirements:

...
        "sacrebleu",
        "safetensors",
        "sentencepiece",
        "sentencepiece>=0.1.94,<0.1.98",
...
       
After removing "sentencepiece>=0.1.94,<0.1.98, at least, I could build eole.

**Comment by vince62s** [comment]
duplicate is a mistake but I can't recall (there was a good reason) why I kept the SP version to <0.1.98

**Comment by robinp** [comment]
Sentencepiece 0.1.99 and later seems to fix some BPE/unigram computation bugs, maybe was fixed at a previous version for "bug-for-bug" compatibility with previous versions? Would be nice to know, otherwise for new models from scratch, new bugfixed sentencepiece is likely better.
